rename the cred to match the saved secrets

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,31 @@ jobs:
       # 4. Build Astro
       - name: Build Astro
         run: npm run build
+        
+      # check ftp 
+      - name: Check FTP secrets
+        shell: bash
+        env:
+          FTP_SERVER: ${{ secrets.FTP_SERVER }}
+          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
+          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
+        run: |
+          if [ -z "$FTP_SERVER" ]; then
+            echo "FTP_SERVER is missing"
+            exit 1
+          fi
+
+          if [ -z "$FTP_USERNAME" ]; then
+            echo "FTP_USERNAME is missing"
+            exit 1
+          fi
+
+          if [ -z "$FTP_PASSWORD" ]; then
+            echo "FTP_PASSWORD is missing"
+            exit 1
+          fi
+
+          echo "All FTP secrets are available."
 
       # 5. Upload dist/ to cPanel
       - name: Upload to cPanel
